language: python
python:
    - "3.5"
    - "3.6"
    - "3.4"
env:
    - DJANGO_VERSION=1.10.6
    - DJANGO_VERSION=1.9.12
    - DJANGO_VERSION=1.8.17
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install django==$DJANGO_VERSION
    - pip install djangorestframework
    - pip install djangorestframework-jwt
    - pip install django-rest-auth
    - pip install django-rest-auth[with_social]
script:
    - python manage.py test
