language: python
python:
    - "3.5"
    - "3.6"
    - "3.4"
env:
    - DJANGO_VERSION=1.10.6
    - DJANGO_VERSION=1.9.12
    - DJANGO_VERSION=1.8.17
install:
    - pip install --upgrade pip
    - pip install -r requirement.txt
before_script:
    - coverage run --source='.' manage.py test TaskApp
    - coverage report
script:
    - python manage.py test
after_success:
    - coveralls